name: test tg bot
on:
  schedule: 
  - cron: "*/15 * * * *"  # schedule tipping to your preference https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events


jobs:
  TipTester:
    runs-on: ubuntu-latest
    
    steps:
    - uses: tellor-io/tipper@master
      with:
        network: "rinkeby" #str: choose between "rinkeby" and "mainnet"
        requestID: 57 # int: the ID of the data type you'd like to tip.
                   # more info at https://www.tellorscan.com/prices
        dataFreshness: "12 hours" # str: the longest duration of time (ex. 1 day, 2 weeks, etc)
                       # you would wait before requesting new on-chain data
                       # for more info, refer to https://www.npmjs.com/package/parse-duration
    - name: Send telegram message if tipping fails
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} failed ${{ repo }} repo name
      env:
        # These secrets will need to be manually added to your repo's secrets on github
        # Please make sure that the github secret names match their names here.
        PUBLIC_KEY: ${{ secrets.TEST_PUBLIC_KEY }} # your account's public key
        PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }} # your account's private key
        MAINNET_NODE: ${{ secrets.MAINNET_NODE }} #your JSON-RPC mainnet endpoint.
        RINKEBY_NODE: ${{ secrets.RINKEBY_NODE }} #your JSON-RPC rinkeby endpoint.
        GOERLI_NODE: ${{ secrets.GOERLI_NODE }} #your JSON-RPC goerli endpoint.
